# Generated by Django 3.2 on 2021-04-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
